name: movie_app
description: A new Flutter movie project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  file: ^6.1.4

  collection: ^1.17.0

  # RiverPod
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.4
  riverpod_annotation: ^2.0.4

  # Screen
  auto_route: ^6.2.0

  # API
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1

  # Model
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Image
  cached_network_image: ^3.2.3

  flutter_rating_bar: ^4.0.1

  sliding_up_panel: ^2.0.0+1

  carousel_slider: ^4.2.1

  # Video
  video_player: ^2.6.1
  youtube_player_flutter: ^8.1.2

  #Loading
  loading_indicator: ^3.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  build_runner: ^2.3.3
  retrofit_generator: ^6.0.0+2

  json_serializable: ^6.6.1


  freezed: ^2.3.2
  auto_route_generator: ^6.2.0

  flutter_gen_runner: ^5.2.0

  riverpod_generator: ^2.1.6

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - lib/config/